### ISSUE TITLE
step-by-step guide

### ISSUE THREAD

**Issue by ghost** [bitcores/pytorch-on-pi-wheel#1]
@bitcores 
- Upload a step-by-step guide, on how to compile Pytorch for Orange Pi.
- Can I build the wheel on my desktop pc, then copy it to orange pi?

**Comment by bitcores** [comment]
I just followed this guide
https://gist.github.com/fgolemo/b973a3fa1aaa67ac61c480ae8440e754
Noting that you should not compile with NO_DISTRIBUTED=0 even if you plan to run it on a cluster.
Technically, you should be able to build it on a PC if you set up a proper environment. I haven't tried.
